name: transmogrify
description: The transmogrify package as featured in the Dart and Flutter Documentation.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

repository: "https://github.com/tolotrasamuel/transmogrify"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
